# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bvbYdgrUtH2PipbudEtUjrzP6aDdkPEx
"""

from fastapi import FastAPI
from pydantic import BaseModel
import pandas as pd
import joblib

app = FastAPI()

# load model
model = joblib.load("app/models/burnout_model.joblib")
scaler = joblib.load("app/models/scaler.joblib")
features = joblib.load("app/models/features.joblib")

risk_labels = {
    0: "Low Risk",
    1: "Medium Risk",
    2: "High Risk"
}

class BurnoutInput(BaseModel):
    Jam_Tidur_Semalam: float
    Seberapa_Sibuk_Anda_Hari_Ini: float
    Seberapa_Banyak_Tugas: float
    Suasana_Hati_Anda: float
    prob_anger: float
    prob_anticipation: float
    prob_disgust: float
    prob_fear: float
    prob_joy: float
    prob_sadness: float

@app.get("/")
def home():
    return {"message": "Burnout API Running"}

@app.post("/predict")
def predict(data: BurnoutInput):

    input_dict = {
        'Jam Tidur Semalam': data.Jam_Tidur_Semalam,
        'Seberapa Sibuk Anda Hari Ini (1-5)': data.Seberapa_Sibuk_Anda_Hari_Ini,
        'Seberapa Banyak Tugas/Pekerjaan (1-5)': data.Seberapa_Banyak_Tugas,
        'Suasana Hati Anda (1-5)': data.Suasana_Hati_Anda,
        'prob_anger': data.prob_anger,
        'prob_anticipation': data.prob_anticipation,
        'prob_disgust': data.prob_disgust,
        'prob_fear': data.prob_fear,
        'prob_joy': data.prob_joy,
        'prob_sadness': data.prob_sadness,
    }

    df = pd.DataFrame([input_dict])

    # urutan feature wajib sama
    df = df[features]

    scaled = scaler.transform(df)

    pred = model.predict(scaled)[0]
    prob = model.predict_proba(scaled)[0]

    return {
        "prediction": int(pred),
        "risk_level": risk_labels[int(pred)],
        "probabilities": {
            "Low Risk": float(prob[0]),
            "Medium Risk": float(prob[1]),
            "High Risk": float(prob[2]),
        }
    }